import type { Metadata } from 'next'
import { Roboto  } from 'next/font/google'
import {cn} from '@/lib/utils'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/ThemeProvider'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})
 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     <body className={cn(poppins.className, "antialiased min-h-screen pt-16")}>
          <ThemeProvider>
            <Navbar />
            {children}
          </ThemeProvider>

      </body>
    </html>
  )
}
